// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: js_engine_grpc.proto

package org.wso2.carbon.identity.graaljs.proto.grpc;

public final class JsEngineGrpcProtos {
  private JsEngineGrpcProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024js_engine_grpc.proto\022-org.wso2.carbon." +
      "identity.graaljs.engine.proto\032\017js_engine" +
      ".proto2\306\002\n\017JsEngineService\022\215\001\n\010Evaluate\022" +
      ">.org.wso2.carbon.identity.graaljs.engin" +
      "e.proto.EvaluateRequest\032?.org.wso2.carbo" +
      "n.identity.graaljs.engine.proto.Evaluate" +
      "Response\"\000\022\242\001\n\017ExecuteCallback\022E.org.wso" +
      "2.carbon.identity.graaljs.engine.proto.E" +
      "xecuteCallbackRequest\032F.org.wso2.carbon." +
      "identity.graaljs.engine.proto.ExecuteCal" +
      "lbackResponse\"\0002\215\004\n\023HostCallbackService\022" +
      "\237\001\n\022InvokeHostFunction\022B.org.wso2.carbon" +
      ".identity.graaljs.engine.proto.HostFunct" +
      "ionRequest\032C.org.wso2.carbon.identity.gr" +
      "aaljs.engine.proto.HostFunctionResponse\"" +
      "\000\022\245\001\n\022GetContextProperty\022E.org.wso2.carb" +
      "on.identity.graaljs.engine.proto.Context" +
      "PropertyRequest\032F.org.wso2.carbon.identi" +
      "ty.graaljs.engine.proto.ContextPropertyR" +
      "esponse\"\000\022\253\001\n\022SetContextProperty\022H.org.w" +
      "so2.carbon.identity.graaljs.engine.proto" +
      ".ContextPropertySetRequest\032I.org.wso2.ca" +
      "rbon.identity.graaljs.engine.proto.Conte" +
      "xtPropertySetResponse\"\0002\256\001\n\030JsEngineStre" +
      "amingService\022\221\001\n\rExecuteScript\022<.org.wso" +
      "2.carbon.identity.graaljs.engine.proto.S" +
      "treamMessage\032<.org.wso2.carbon.identity." +
      "graaljs.engine.proto.StreamMessage\"\000(\0010\001" +
      "BC\n+org.wso2.carbon.identity.graaljs.pro" +
      "to.grpcB\022JsEngineGrpcProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.wso2.carbon.identity.graaljs.proto.JsEngineProtos.getDescriptor(),
        });
    org.wso2.carbon.identity.graaljs.proto.JsEngineProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
